//! Folds this guest's ABI method identities in at build time.
//!
//! The Starstream compiler identifies each method by `sha256` of its source
//! name (`snake_case`), split into four little-endian `u64` words — the scheme
//! verified against `example.wasm`. We compute those here with `sha2` and emit
//! one `const` per method into `$OUT_DIR/method_hashes.rs`, so the guest carries
//! no SHA-256 code at run time (cf. the host, which hashes export names
//! discovered at run time and so keeps `sha2` as a normal dependency).

use std::env;
use std::fs;
use std::path::Path;

use sha2::{Digest, Sha256};

/// The ABI methods this UTXO implements, by their Starstream source name
/// (`snake_case`). Each gets a generated hash `const`; a method left out is not
/// declared via `implements-method` and so the host will not let it be called.
const METHODS: [&str; 4] = ["plus_chips", "plus_mult", "mult_mult", "finish"];

/// `sha256(name)` as four little-endian `u64` words.
fn method_hash(name: &str) -> (u64, u64, u64, u64) {
    let digest = Sha256::digest(name.as_bytes());
    let word =
        |i: usize| u64::from_le_bytes(digest[i * 8..i * 8 + 8].try_into().expect("8-byte word"));
    (word(0), word(1), word(2), word(3))
}

fn main() {
    let mut code = String::from(
        "// @generated by build.rs — ABI method identities (sha256 of each\n\
         // Starstream source name, as four little-endian u64 words).\n\n",
    );

    // One `const` per method, named after the method in SCREAMING_SNAKE_CASE…
    for name in METHODS {
        let (a, b, c, d) = method_hash(name);
        let ident = name.to_uppercase();
        code.push_str(&format!(
            "pub const {ident}: (u64, u64, u64, u64) = ({a}, {b}, {c}, {d});\n"
        ));
    }

    // …and a `(name, hash)` table for the constructor to iterate.
    code.push_str(&format!(
        "\npub const METHODS: [(&str, (u64, u64, u64, u64)); {}] = [\n",
        METHODS.len()
    ));
    for name in METHODS {
        let ident = name.to_uppercase();
        code.push_str(&format!("    ({name:?}, {ident}),\n"));
    }
    code.push_str("];\n");

    let out = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    fs::write(Path::new(&out).join("method_hashes.rs"), code).expect("write method_hashes.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
